name: My Panda CI
on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest
    name: My Build
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
      - name: Setup Go environment
        uses: actions/setup-go@v5.2.0
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
          go-version: 1.17.0

      - name: what is go version and run test
        run: |
          go version
          ls
          cd ./Activity1d_TestGoblin
          go test -cover

      - name: Checkout private repo remotely
        uses: actions/checkout@v2
        with:
          repository: EdythHo/sickandhiding
          path: edythfolder
          token: ${{secrets.EDYTH}}

      - name: Show hidden file
        run: |
          ls
          cd edythfolder
          ls
          cat README.md

      - name: Discord Message
        # You may pin to the exact commit or the version.
        # uses: discord-actions/message@5c7149c81a83146e5d01f142be1bf87a61831c4d
        uses: discord-actions/message@v2
        with:
          # A Discord webhook URL
          webhookUrl: ${{secrets.DISCORD}}
          # A message to send to Discord
          message: hello 
          # A username for the message
          username: guesswho
          # Token
          # An avatar for the message
          # avatar: # optional

      # - name: Send Discord Webhook
      #   # You may pin to the exact commit or the version.
      #   # uses: hugoalh/send-discord-webhook-ghaction@2c03ad0b59b889bc8c6385b7e8fdda3995add207
      #   uses: hugoalh/send-discord-webhook-ghaction@v7.0.3
      #   with:
      #     # {string} Discord webhook key.
      #     key: ${{secrets.DISCORD}}
      #     # {string} Message content.
      #     content: hello from anisha
          
                
      
            
